### ISSUE TITLE
Unable to 100% complete temple quests

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#231]
When trying to complete the Power from Beyond temple quests, Vladimir stops giving quests before all undiscovered temples are found. 

---

## Details 
Quest ID from console:
	help MQ_TempleQuest_01
	----CONSOLE COMMANDS-------------------
	----SCRIPT FUNCTIONS-------------------
	----VIEWER STRINGS NOT AVAILABLE-------
	----GLOBAL VARIABLES-------------------
	----OTHER FORMS-------------------
	SCEN: MQ_TempleQuest_01_TL (000854DE) ''
	QUST: MQ_TempleQuest_01 (000854E8) 'Power from Beyond'

Just before completing the 23rd temple quest (this is the last one Vladimir will give)
	player.sqs 854E8
	Quest: MQ_TempleQuest_01 - Running - Current Stage: 20
	(not set)	0
	(done)	5
	(done)	5
	(not set)	7
	(done)	10
	(not set)	12
	(not set)	13
	(done)	20
	(not set)	30
	(not set)	50
	(not set)	60
	(not set)	60

After completing the 23rd temple quest (Vladimir doesn't talk or give anymore temple quests)
	player.sqs 854E8
	Quest: MQ_TempleQuest_01 - Stopped
	(not set)	0
	(done)	5
	(done)	5
	(not set)	7
	(done)	10
	(not set)	12
	(not set)	13
	(done)	20
	(done)	30
	(done)	50
	(done)	60
	(done)	60

## Game Version
1.7.29

## New Game
No

## Reproduction Steps
I didn't noticed this on the original game since I did not get all powers the first time through, but in NG+ I skip the main quest and complete Among the Stars and Revelation first. After completing Revelation and the armillary and before finding any temples, the powers page shows 27 undiscovered temples. Completing the Powers from Beyond quest and Barret's power quest will leave me with anywhere from 3 to 5 unknown temples, and Vladimir does not give any further quests. After reaching the sticking point with Vladimir, I have tried visiting every single system in the star map and not 'found' any further anomalies. Resting for several days doesn't allow the quest to retrigger, nor does exiting and reloading the game. I get the same issue every NG+. 

I have also seen this reported on Reddit. 
Examples: https://www.reddit.com/r/Starfield/comments/16hwyqt/i_am_missing_4_temples_and_need_assistance/
and https://www.reddit.com/r/Starfield/comments/168q9to/undiscovered_temples/
There are others if you search undiscovered temples.
 

Given that there are only 24 powers and 24 artifacts, I am sure the 27 undiscovered temples is a bug, and there will always be 3 undiscovered temples at minimum. Sometimes there's more. This time I had 4 undiscovered temples after Barrett's quest and 23 temples.

**Comment by zarantha** [comment]
Screenshots of the powers menu at various stages.

![After completing Revelation and before finding Temples](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/31942539/a7f5d5f8-f7f6-45c5-9f41-4d6303230600)
![After discovering the first artifact in NG+](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/31942539/9101b9da-cdc2-4de2-9907-ef651ea5459b)
![Before starting the main quest after NG+](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/31942539/7b9fbda5-74bb-48df-ba09-82325c9bf2e9)
![Unable to get more Temple quests and Barrett's quest is finished](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/31942539/1dc1fe72-7d2b-4492-94c9-5e38f2a29c69)

**Comment by zarantha** [comment]
This issue is fixed with this mod:
https://www.nexusmods.com/starfield/mods/5114

**Comment by Constellation-VASCO** [comment]
Now it is my understanding that this mod has been flagged as fixed, but has also been taken under consideration that if you are in NG+ and skip the main storyline you get to discover three temples straight away (including the Sigma temple from the glitched out Worlds apart story arc)? I'm asking cause due to the fact that you get the three artifacts normally required for finding these temples are given to you after you got the quest from Vladimir this means that you end up with three undiscovered temples. It is also of note that the Sigma temple you visit with Barrett will actually be a 2nd temple (so it is not the same as one of the aforementioned three temples, Sigma being one of which, you can instantly find upon starting and choosing to skip the main story)

**Comment by Constellation-VASCO** [comment]
meant bug, not mod, obviously ^^

**Comment by Constellation-VASCO** [comment]
Does this fix work for a new game playthrough? Downloaded the mod listed above and saw that the fix is part of the community patch but it still shows all powers and 2 undiscovered temples. And Vlad has nothing for me.
